### PR TITLE
Fix parenthesis in links and images

### LINKED ISSUE #61: Parenthesis in links or images
markup-it fails to parse links with an href containing parenthesis.

For example with the following markdown:

```markdown
- [Test](hello(world).md)
```

markdown-it and GitHub correctly parses it as a link with href: `hello(world).md`. But `markup-it` fails.

When stringifying to Markdown, we should maybe also escape the parenthesis in links.

Related: https://github.com/GitbookIO/feedback/issues/386

### PR DESCRIPTION
**Pull request by SamyPesse**
This PR fixes #61.

- [x] Escape parenthesis in links
- [x] Parse correctly links with parenthesis
- [x] Escape parenthesis in images
- [x] Parse correctly images with parenthesis
- [x] Test everything!
- [x] Backward compatibility with `kramed`
- [x] Add escaping for code block syntax

### CODE REVIEW

**Comment by SamyPesse** [comment]
@Soreine I just have a last change to finish, but can you review this PR and push your branch for HTML fixes?

Basically this PR improves the escaping/unescaping of urls. It escapes only parenthesis and whitespaces (`[test](hello world.md)` doesn't work on GitHub), but it escapes almost everything correctly.

File: src/markdown/blocks/code.js [hunk 1]
```diff
@@ -56,8 +63,9 @@ const deserializeFences = Deserializer()
         // Extract language syntax
         let data;
         if (Boolean(match[2])) {
+            console.log('unescape', match[2], utils.unescape(match[2].trim()));
```
Comment (Soreine) [inline src/markdown/blocks/code.js]: Console.log
